# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  config.vm.box = "mepc"

  config.vm.box_url = "http://filer/mepc.box"
  config.ssh.private_key_path = "mepc.pem"
  config.vm.network :bridged, :mac => '02000000{{ mac }}'

  config.vm.host_name = '{{ fqdn }}'

  config.vm.provision :puppet_server do |puppet|
    puppet.puppet_server = '{{ puppetmaster }}.mepc.lan'
    puppet.puppet_node = '{{ fqdn }}'
    puppet.options = ["--verbose"]
  end 
end
